### ISSUE TITLE
Crash Windows 8.1 

### ISSUE THREAD

**Issue by Chris-Barton** [aauren/SpotifyToaster#20]
Windows 8.1 
Spotify 1.0.6.80.g2a801a53

Got this when ddebbuging in VS 2013

![image](https://cloud.githubusercontent.com/assets/8409186/8070344/795d5522-0ef8-11e5-8f95-c48ce51a0efc.png)

**Comment by aauren** [comment]
Thanks for opening this issue. Unfortunately, I don't have a Windows computer at the moment to continue development. I hope to obtain one soon. In the mean time... Can you tell me more about the error?

* Does this happen for you all the time? Or on a specific track?
* What were you doing directly before the error occurred?
* Can you send me the Call Stack from both this exception and the Exception that was thrown above it ("Invalid URI: The format of the UR...")?
* What was the name of your Spotify window at the time you received the error?
* I'm not sure how much experience you have with the VS debugger, but it would be really helpful if you were able to tell me what was in ```getCurrentTrackInfo()``` at the time of the error.

If I had to guess, I would say that at the time of the error your Spotify window did not contain both the artist and track name. The ```getCurrentTrackInfo()``` method tries to split the Spotify Window title into two parts, the artist and track name and return them as an array. The artist being at index 0 and the track being at index 1.

Inside ```getTrack()``` (where the error occurs), it checks to make sure that the ```getCurrenTrackInfo()``` array is not blank and has more than 1 element, but it was short sighted in not making sure that there were at least 2 elements in there. This is something I would like to remedy when I get a Windows machine to make a new binary. The point being, that the error you are receiving most likely comes from there not being a second item in that array (array index 1) because there was no track name.

**Comment by Chris-Barton** [comment]
Ive tried to compile the github version but your missing the protectedReasorces.res and some others check your uploading all you properties folder
 
so i cant debug it properly 

its every time you change song it crashes however no error message will popup unless you run it in the debuger

if i can get it to compile ill let you know

**Comment by aauren** [comment]
The missing protectedResources.res file was purposeful so that I didn't have to share my API keys to LastFM. See the [contribution section of the ReadMe](https://github.com/aauren/SpotifyToaster#contribution) for information on how to properly add that back to the project with your own generated API keys in order to build the project.

**Comment by Chris-Barton** [comment]
Yer just going throught the signing up process

**Comment by Chris-Barton** [comment]
Ok so got it running would a call stack help not used to c# /.net more of a c++ developer

**Comment by Chris-Barton** [comment]
![image](https://cloud.githubusercontent.com/assets/8409186/8091794/f3d32632-0fad-11e5-8a58-4d9ba0c3484e.png)
 This is where it beaks

![image](https://cloud.githubusercontent.com/assets/8409186/8091811/0ef1af2e-0fae-11e5-8edb-191304c1fa78.png)

Call stack

**Comment by aauren** [comment]
Can you send me:
* The contents of ```getCurrentTrackInfo()``` ?
* The full title of your Spotify Window?

**Comment by Chris-Barton** [comment]
![image](https://cloud.githubusercontent.com/assets/8409186/8091998/f484213e-0fae-11e5-9cad-813de544c794.png)

**Comment by Chris-Barton** [comment]
change to 0 fix but dont know if works cross platform also mod tracks dont fit on popup

**Comment by Chris-Barton** [comment]
*most

**Comment by Chris-Barton** [comment]
sorry head up both 

getTrack()
getArtist() 

Return this  "Iron Maiden - The Number Of The Beast - 1998 Remastered Version"
i.e                Artist     -        Track

**Comment by aauren** [comment]
Yeah, that's really helpful. It looks like the split on the "en dash" (/u2013) in ```getCurrentTrackInfo()``` isn't working any longer since both the artist and track are being combined into index 0 instead of being split like they were supposed to. If you want you can play around with the split code inside ```getCurrentTrackInfo()``` and see if you can get it working. Otherwise, I should be getting my hands on a Windows machine soon here and I'll be able to start debugging it.

It would also be good if it took into account tracks like the Iron Maiden one you pointed out that have dashes as part of the track name, since as the code is now "1998 Remastered Version" would go into index 3 (if it was properly splitting) and wouldn't show up in the track name.

**Comment by Chris-Barton** [comment]
have some ideas but do you know the max number of characters

**Comment by Chris-Barton** [comment]
per line

**Comment by Chris-Barton** [comment]
Fixed it

Changed

if (!string.IsNullOrEmpty(currentTrack))
{
         strArray = currentTrack.Split('\u2013');
}

To

if (!string.IsNullOrEmpty(currentTrack))
{
    strArray = currentTrack.Split('-');
}

If this doesn't work on non-windows OS i dont no the equivilent in C# but in c++ you can use

#ifdef _WIN32
